spring:
  datasource: # mysql 관련 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MY_SQL_ADDRESS_YOURNET}
    username: ${MY_SQL_ID}
    password: ${MY_SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # 서버 시작 시 변경사항만 update
    show-sql: false      # 쿼리문 보여줌
    properties:
      hibernate:
        format_sql: false  # 쿼리문 가독성 있게 띄워줌